-- StuffApp Schema
-- All tables use TEXT primary keys (UUID)

CREATE TABLE IF NOT EXISTS watches (
    id TEXT PRIMARY KEY,
    brand TEXT,
    model TEXT,
    metal TEXT,
    case_diameter REAL,
    reference TEXT,
    dial_color TEXT,
    case_num TEXT,
    movement_num TEXT,
    edition TEXT,
    year INTEGER,
    calibre TEXT,
    movement_type TEXT,
    movement_jewels INTEGER,
    movement_origin TEXT,
    beat INTEGER,
    reserve REAL,
    complications TEXT,
    clasp_type TEXT,
    lug_mm REAL,
    strap_material TEXT,
    strap_color TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    service_date DATE,
    value REAL,
    results TEXT,
    value_searched_at TEXT,
    description TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image_obv TEXT,
    image_rev TEXT,
    receipt TEXT,
    document TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS coins (
    id TEXT PRIMARY KEY,
    coin_id TEXT,
    authority TEXT,
    region TEXT,
    denomination TEXT,
    metal TEXT,
    mint TEXT,
    date_1 INTEGER,
    date_1_text TEXT,
    date_2 INTEGER,
    date_2_text TEXT,
    description TEXT,
    coin_references TEXT,
    notes TEXT,
    grade TEXT,
    die_axis TEXT,
    strike REAL,
    surface REAL,
    weight REAL,
    size REAL,
    bullion TEXT,
    bin TEXT,
    storage_location TEXT,
    sheldon TEXT,
    obv_rev TEXT,
    condition TEXT,
    received TEXT,
    print_field TEXT,
    price REAL,
    vendor TEXT,
    purchase_date DATE,
    owner TEXT,
    property_name TEXT,
    status TEXT,
    image_1 TEXT,
    image_2 TEXT,
    receipt TEXT,
    document_1 TEXT,
    document_2 TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS cameras (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    digital_film TEXT,
    film_size TEXT,
    lens_mount TEXT,
    megapixels REAL,
    sensor TEXT,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS lenses (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    mount TEXT,
    aperture REAL,
    filter_size REAL,
    length REAL,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS pens (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    type TEXT,
    action TEXT,
    nib TEXT,
    cartridge TEXT,
    reservoir TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS art (
    id TEXT PRIMARY KEY,
    title TEXT,
    artist TEXT,
    year INTEGER,
    medium TEXT,
    dimensions TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    location TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS vehicles (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    year INTEGER,
    vin TEXT,
    state TEXT,
    tags TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    insurance TEXT,
    invoice TEXT,
    registration TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS recordings (
    id TEXT PRIMARY KEY,
    title TEXT,
    artist TEXT,
    type TEXT,
    genre TEXT,
    genre_2 TEXT,
    year_recorded TEXT,
    speed TEXT,
    sound TEXT,
    like_field TEXT,
    number_position INTEGER,
    other TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS rifles (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    caliber TEXT,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS credit_cards (
    id TEXT PRIMARY KEY,
    name TEXT,
    number TEXT,
    cvc TEXT,
    cvc_2 TEXT,
    expiration DATE,
    description TEXT,
    billing_address TEXT,
    billing_short TEXT,
    owner TEXT,
    image_front TEXT,
    image_back TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS properties (
    id TEXT PRIMARY KEY,
    name TEXT,
    short_name TEXT,
    type TEXT,
    address TEXT,
    year_built INTEGER,
    ein TEXT,
    llc TEXT,
    wifi TEXT,
    wifi_name TEXT,
    alarm_company TEXT,
    alarm_account TEXT,
    alarm_code_1 TEXT,
    alarm_password TEXT,
    alarm_phone TEXT,
    alarm_notes TEXT,
    date DATE,
    price REAL,
    notes TEXT,
    status TEXT,
    owner TEXT,
    archive TEXT,
    image TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS audio (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    type TEXT,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS topics (
    id TEXT PRIMARY KEY,
    property_id TEXT,
    subject TEXT,
    body TEXT,
    image TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_topics_property_id ON topics(property_id);

CREATE TABLE IF NOT EXISTS persons (
    id TEXT PRIMARY KEY,
    name TEXT,
    phone TEXT,
    home_address TEXT,
    birth_date DATE,
    blood_type TEXT,
    ssn TEXT,
    spouse TEXT,
    spouse_name_and_phone TEXT,
    primary_care_physician TEXT,
    prescriptions TEXT,
    health_notes TEXT,
    owner TEXT,
    notes TEXT,
    text_1 TEXT,
    text_2 TEXT,
    text_3 TEXT,
    text_4 TEXT,
    head_shot TEXT,
    image_1 TEXT,
    image_7 TEXT,
    image_9 TEXT,
    image_text_1 TEXT,
    image_text_2 TEXT,
    image_text_3 TEXT,
    image_text_4 TEXT,
    image_text_5 TEXT,
    image_text_6 TEXT,
    image_text_7 TEXT,
    image_text_8 TEXT,
    image_text_9 TEXT,
    license_obverse TEXT,
    license_reverse TEXT,
    passport TEXT,
    medicare TEXT,
    health_card_obv TEXT,
    health_card_rev TEXT,
    global_entry TEXT,
    eye_prescription TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);
