-- StuffApp Schema
-- All tables use TEXT primary keys (UUID)

-- Users + per-category authorization. The Cloudflare Access edge
-- authenticates a user by email; this table maps that email to a set
-- of allowed categories (CSV of slugs, or '*' for owner = everything).
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    role TEXT DEFAULT 'member',          -- 'owner' or 'member'
    categories TEXT DEFAULT '',          -- '*' for owner, else CSV of slugs
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS watches (
    id TEXT PRIMARY KEY,
    brand TEXT,
    model TEXT,
    metal TEXT,
    case_diameter REAL,
    reference TEXT,
    dial_color TEXT,
    case_num TEXT,
    movement_num TEXT,
    edition TEXT,
    year INTEGER,
    calibre TEXT,
    movement_type TEXT,
    movement_jewels INTEGER,
    movement_origin TEXT,
    escapement TEXT,
    beat INTEGER,
    reserve REAL,
    complications TEXT,
    clasp_type TEXT,
    lug_mm REAL,
    strap_material TEXT,
    strap_color TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    service_date DATE,
    value REAL,
    results TEXT,
    value_searched_at TEXT,
    description TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image_obv TEXT,
    image_rev TEXT,
    receipt TEXT,
    container_1 TEXT,
    container_2 TEXT,
    document TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS watch_service_events (
    id TEXT PRIMARY KEY,
    watch_id TEXT NOT NULL,
    date_sent DATE,
    vendor TEXT,
    reason TEXT,
    cost TEXT,
    date_returned DATE,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (watch_id) REFERENCES watches(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS coins (
    id TEXT PRIMARY KEY,
    coin_id TEXT,
    authority TEXT,
    region TEXT,
    denomination TEXT,
    metal TEXT,
    mint TEXT,
    date_1 INTEGER,
    date_1_text TEXT,
    date_2 INTEGER,
    date_2_text TEXT,
    description TEXT,
    coin_references TEXT,
    notes TEXT,
    grade TEXT,
    die_axis TEXT,
    strike REAL,
    surface REAL,
    weight REAL,
    size REAL,
    bullion TEXT,
    bin TEXT,
    storage_location TEXT,
    sheldon TEXT,
    obv_rev TEXT,
    condition TEXT,
    received TEXT,
    print_field TEXT,
    price REAL,
    vendor TEXT,
    purchase_date DATE,
    owner TEXT,
    property_name TEXT,
    status TEXT,
    image_1 TEXT,
    image_2 TEXT,
    receipt TEXT,
    document_1 TEXT,
    document_2 TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS cameras (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    digital_film TEXT,
    film_size TEXT,
    lens_mount TEXT,
    megapixels REAL,
    sensor TEXT,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS lenses (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    mount TEXT,
    aperture REAL,
    filter_size REAL,
    length REAL,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS pens (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    type TEXT,
    action TEXT,
    nib TEXT,
    cartridge TEXT,
    reservoir TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS art (
    id TEXT PRIMARY KEY,
    title TEXT,
    artist TEXT,
    year INTEGER,
    medium TEXT,
    dimensions TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    location TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    doc_2 TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS items (
    id TEXT PRIMARY KEY,
    name TEXT,
    type TEXT,
    subtype TEXT,
    make TEXT,
    model TEXT,
    serial TEXT,
    year INTEGER,
    description TEXT,
    notes TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    value REAL,
    warranty_until DATE,
    owner TEXT,
    property TEXT,
    location TEXT,
    status TEXT,
    location_status TEXT,
    image TEXT,
    documents TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS vehicles (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    year INTEGER,
    vin TEXT,
    state TEXT,
    tags TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    insurance TEXT,
    invoice TEXT,
    registration TEXT,
    vehicle_doc_5 TEXT, vehicle_doc_5_title TEXT,
    vehicle_doc_6 TEXT, vehicle_doc_6_title TEXT,
    vehicle_doc_7 TEXT, vehicle_doc_7_title TEXT,
    vehicle_doc_8 TEXT, vehicle_doc_8_title TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS recordings (
    id TEXT PRIMARY KEY,
    title TEXT,
    artist TEXT,
    type TEXT,
    genre TEXT,
    genre_2 TEXT,
    year_recorded TEXT,
    speed TEXT,
    sound TEXT,
    like_field TEXT,
    number_position INTEGER,
    other TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS rifles (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    caliber TEXT,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS credit_cards (
    id TEXT PRIMARY KEY,
    name TEXT,
    number TEXT,
    cvc TEXT,
    cvc_2 TEXT,
    expiration DATE,
    description TEXT,
    billing_address TEXT,
    billing_short TEXT,
    owner TEXT,
    image_front TEXT,
    image_back TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS properties (
    id TEXT PRIMARY KEY,
    name TEXT,
    short_name TEXT,
    type TEXT,
    address TEXT,
    year_built INTEGER,
    ein TEXT,
    llc TEXT,
    wifi TEXT,
    wifi_name TEXT,
    date DATE,
    price REAL,
    notes TEXT,
    status TEXT,
    owner TEXT,
    archive TEXT,
    image TEXT,
    doc_1 TEXT, doc_1_title TEXT,
    doc_2 TEXT, doc_2_title TEXT,
    doc_3 TEXT, doc_3_title TEXT,
    doc_4 TEXT, doc_4_title TEXT,
    doc_5 TEXT, doc_5_title TEXT,
    doc_6 TEXT, doc_6_title TEXT,
    doc_7 TEXT, doc_7_title TEXT,
    doc_8 TEXT, doc_8_title TEXT,
    doc_9 TEXT, doc_9_title TEXT,
    doc_10 TEXT, doc_10_title TEXT,
    alarm_codes_entry_1 TEXT, alarm_codes_code_1 TEXT, alarm_codes_note_1 TEXT,
    alarm_codes_entry_2 TEXT, alarm_codes_code_2 TEXT, alarm_codes_note_2 TEXT,
    alarm_codes_entry_3 TEXT, alarm_codes_code_3 TEXT, alarm_codes_note_3 TEXT,
    alarm_codes_entry_4 TEXT, alarm_codes_code_4 TEXT, alarm_codes_note_4 TEXT,
    alarm_codes_entry_5 TEXT, alarm_codes_code_5 TEXT, alarm_codes_note_5 TEXT,
    alarm_codes_entry_6 TEXT, alarm_codes_code_6 TEXT, alarm_codes_note_6 TEXT,
    alarm_codes_entry_7 TEXT, alarm_codes_code_7 TEXT, alarm_codes_note_7 TEXT,
    alarm_codes_entry_8 TEXT, alarm_codes_code_8 TEXT, alarm_codes_note_8 TEXT,
    people_name_1 TEXT, people_role_1 TEXT, people_phone_1 TEXT, people_email_1 TEXT, people_note_1 TEXT,
    people_name_2 TEXT, people_role_2 TEXT, people_phone_2 TEXT, people_email_2 TEXT, people_note_2 TEXT,
    people_name_3 TEXT, people_role_3 TEXT, people_phone_3 TEXT, people_email_3 TEXT, people_note_3 TEXT,
    people_name_4 TEXT, people_role_4 TEXT, people_phone_4 TEXT, people_email_4 TEXT, people_note_4 TEXT,
    people_name_5 TEXT, people_role_5 TEXT, people_phone_5 TEXT, people_email_5 TEXT, people_note_5 TEXT,
    people_name_6 TEXT, people_role_6 TEXT, people_phone_6 TEXT, people_email_6 TEXT, people_note_6 TEXT,
    people_name_7 TEXT, people_role_7 TEXT, people_phone_7 TEXT, people_email_7 TEXT, people_note_7 TEXT,
    people_name_8 TEXT, people_role_8 TEXT, people_phone_8 TEXT, people_email_8 TEXT, people_note_8 TEXT,
    people_name_9 TEXT, people_role_9 TEXT, people_phone_9 TEXT, people_email_9 TEXT, people_note_9 TEXT,
    people_name_10 TEXT, people_role_10 TEXT, people_phone_10 TEXT, people_email_10 TEXT, people_note_10 TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS audio (
    id TEXT PRIMARY KEY,
    make TEXT,
    model TEXT,
    type TEXT,
    serial_number TEXT,
    date DATE,
    price REAL,
    vendor TEXT,
    notes TEXT,
    owner TEXT,
    property TEXT,
    status TEXT,
    image TEXT,
    receipt TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS topics (
    id TEXT PRIMARY KEY,
    property_id TEXT,
    subject TEXT,
    body TEXT,
    image TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_topics_property_id ON topics(property_id);
CREATE INDEX IF NOT EXISTS idx_watch_service_events_watch_id
    ON watch_service_events(watch_id);

CREATE TABLE IF NOT EXISTS persons (
    id TEXT PRIMARY KEY,
    name TEXT,
    phone TEXT,
    home_address TEXT,
    birth_date DATE,
    blood_type TEXT,
    ssn TEXT,
    spouse TEXT,
    spouse_name_and_phone TEXT,
    primary_care_physician TEXT,
    prescriptions TEXT,
    health_notes TEXT,
    owner TEXT,
    notes TEXT,
    text_1 TEXT,
    text_2 TEXT,
    text_3 TEXT,
    text_4 TEXT,
    head_shot TEXT,
    image_1 TEXT,
    image_7 TEXT,
    image_9 TEXT,
    image_text_1 TEXT,
    image_text_2 TEXT,
    image_text_3 TEXT,
    image_text_4 TEXT,
    image_text_5 TEXT,
    image_text_6 TEXT,
    image_text_7 TEXT,
    image_text_8 TEXT,
    image_text_9 TEXT,
    license_obverse TEXT,
    license_reverse TEXT,
    license_number TEXT,
    passport TEXT,
    passport_number TEXT,
    medicare TEXT,
    medicare_number TEXT,
    health_card_obv TEXT,
    health_card_rev TEXT,
    health_insurance_number TEXT,
    other_health_1 TEXT,
    other_health_2 TEXT,
    global_entry TEXT,
    global_entry_number TEXT,
    eye_prescription TEXT,
    med_name_1 TEXT, med_type_1 TEXT, med_active_ingredients_1 TEXT, med_dose_1 TEXT, med_directions_1 TEXT, med_note_1 TEXT,
    med_name_2 TEXT, med_type_2 TEXT, med_active_ingredients_2 TEXT, med_dose_2 TEXT, med_directions_2 TEXT, med_note_2 TEXT,
    med_name_3 TEXT, med_type_3 TEXT, med_active_ingredients_3 TEXT, med_dose_3 TEXT, med_directions_3 TEXT, med_note_3 TEXT,
    med_name_4 TEXT, med_type_4 TEXT, med_active_ingredients_4 TEXT, med_dose_4 TEXT, med_directions_4 TEXT, med_note_4 TEXT,
    med_name_5 TEXT, med_type_5 TEXT, med_active_ingredients_5 TEXT, med_dose_5 TEXT, med_directions_5 TEXT, med_note_5 TEXT,
    med_name_6 TEXT, med_type_6 TEXT, med_active_ingredients_6 TEXT, med_dose_6 TEXT, med_directions_6 TEXT, med_note_6 TEXT,
    med_name_7 TEXT, med_type_7 TEXT, med_active_ingredients_7 TEXT, med_dose_7 TEXT, med_directions_7 TEXT, med_note_7 TEXT,
    med_name_8 TEXT, med_type_8 TEXT, med_active_ingredients_8 TEXT, med_dose_8 TEXT, med_directions_8 TEXT, med_note_8 TEXT,
    med_name_9 TEXT, med_type_9 TEXT, med_active_ingredients_9 TEXT, med_dose_9 TEXT, med_directions_9 TEXT, med_note_9 TEXT,
    med_name_10 TEXT, med_type_10 TEXT, med_active_ingredients_10 TEXT, med_dose_10 TEXT, med_directions_10 TEXT, med_note_10 TEXT,
    med_name_11 TEXT, med_type_11 TEXT, med_active_ingredients_11 TEXT, med_dose_11 TEXT, med_directions_11 TEXT, med_note_11 TEXT,
    med_name_12 TEXT, med_type_12 TEXT, med_active_ingredients_12 TEXT, med_dose_12 TEXT, med_directions_12 TEXT, med_note_12 TEXT,
    med_name_13 TEXT, med_type_13 TEXT, med_active_ingredients_13 TEXT, med_dose_13 TEXT, med_directions_13 TEXT, med_note_13 TEXT,
    med_name_14 TEXT, med_type_14 TEXT, med_active_ingredients_14 TEXT, med_dose_14 TEXT, med_directions_14 TEXT, med_note_14 TEXT,
    med_name_15 TEXT, med_type_15 TEXT, med_active_ingredients_15 TEXT, med_dose_15 TEXT, med_directions_15 TEXT, med_note_15 TEXT,
    med_name_16 TEXT, med_type_16 TEXT, med_active_ingredients_16 TEXT, med_dose_16 TEXT, med_directions_16 TEXT, med_note_16 TEXT,
    med_name_17 TEXT, med_type_17 TEXT, med_active_ingredients_17 TEXT, med_dose_17 TEXT, med_directions_17 TEXT, med_note_17 TEXT,
    med_name_18 TEXT, med_type_18 TEXT, med_active_ingredients_18 TEXT, med_dose_18 TEXT, med_directions_18 TEXT, med_note_18 TEXT,
    med_name_19 TEXT, med_type_19 TEXT, med_active_ingredients_19 TEXT, med_dose_19 TEXT, med_directions_19 TEXT, med_note_19 TEXT,
    med_name_20 TEXT, med_type_20 TEXT, med_active_ingredients_20 TEXT, med_dose_20 TEXT, med_directions_20 TEXT, med_note_20 TEXT,
    med_name_21 TEXT, med_type_21 TEXT, med_active_ingredients_21 TEXT, med_dose_21 TEXT, med_directions_21 TEXT, med_note_21 TEXT,
    med_name_22 TEXT, med_type_22 TEXT, med_active_ingredients_22 TEXT, med_dose_22 TEXT, med_directions_22 TEXT, med_note_22 TEXT,
    med_name_23 TEXT, med_type_23 TEXT, med_active_ingredients_23 TEXT, med_dose_23 TEXT, med_directions_23 TEXT, med_note_23 TEXT,
    med_name_24 TEXT, med_type_24 TEXT, med_active_ingredients_24 TEXT, med_dose_24 TEXT, med_directions_24 TEXT, med_note_24 TEXT,
    id_doc_3 TEXT, id_doc_3_title TEXT,
    id_doc_4 TEXT, id_doc_4_title TEXT,
    id_doc_5 TEXT, id_doc_5_title TEXT,
    id_doc_6 TEXT, id_doc_6_title TEXT,
    id_doc_7 TEXT, id_doc_7_title TEXT,
    id_doc_8 TEXT, id_doc_8_title TEXT,
    health_doc_3 TEXT, health_doc_3_title TEXT,
    health_doc_4 TEXT, health_doc_4_title TEXT,
    health_doc_5 TEXT, health_doc_5_title TEXT,
    health_doc_6 TEXT, health_doc_6_title TEXT,
    health_doc_7 TEXT, health_doc_7_title TEXT,
    health_doc_8 TEXT, health_doc_8_title TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

-- Tombstones for deletes that the incremental Files sync needs to
-- propagate to the local StuffFiles folder. Every server-side delete
-- of a referenced file (UI X-button, record DELETE, etc.) writes a
-- row capturing enough info to reconstruct the export-shaped local
-- path: StuffFiles/<cat_label>/<group_path>/<ident_path> — <label>.<ext>.
-- The /export-files endpoint surfaces deletions newer than the
-- client's `since` timestamp inside `_tombstones.json` so syncDown
-- can remove the matching local files.
CREATE TABLE IF NOT EXISTS tombstones (
    id TEXT PRIMARY KEY,
    category TEXT,
    cat_label TEXT,
    group_path TEXT,
    ident_path TEXT,
    label TEXT,
    filename TEXT,
    deleted_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_tombstones_deleted_at ON tombstones(deleted_at);

-- Native mobile clients keep a local read cache. File tombstones above
-- remove local bytes; these record tombstones remove deleted rows.
CREATE TABLE IF NOT EXISTS mobile_record_tombstones (
    id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    record_id TEXT NOT NULL,
    deleted_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_mobile_record_tombstones_deleted_at
    ON mobile_record_tombstones(deleted_at);
